### ISSUE TITLE
CI/CD 구축하기

### ISSUE THREAD

**Issue by Taejin1221** [KakaoTech-BootCamp-Team-2/Kaboo-Auth#5]
### TODO
- [x] 도커 파일 작성
- [x] 도커 컴포즈 파일 작성
- [x] Github Action 추가
- [x] EC2 연결
- [x] 트리거 감지, 자동 배포

**Comment by pjh5365** [comment]
배포 완료 👍
